server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: eureka-naming-server
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
